/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as YearMonthDayDetectionsImport } from './routes/$year/$month/$day/detections'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const YearMonthDayDetectionsRoute = YearMonthDayDetectionsImport.update({
  id: '/$year/$month/$day/detections',
  path: '/$year/$month/$day/detections',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$year/$month/$day/detections': {
      id: '/$year/$month/$day/detections'
      path: '/$year/$month/$day/detections'
      fullPath: '/$year/$month/$day/detections'
      preLoaderRoute: typeof YearMonthDayDetectionsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$year/$month/$day/detections': typeof YearMonthDayDetectionsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$year/$month/$day/detections': typeof YearMonthDayDetectionsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$year/$month/$day/detections': typeof YearMonthDayDetectionsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$year/$month/$day/detections'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$year/$month/$day/detections'
  id: '__root__' | '/' | '/$year/$month/$day/detections'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YearMonthDayDetectionsRoute: typeof YearMonthDayDetectionsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YearMonthDayDetectionsRoute: YearMonthDayDetectionsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$year/$month/$day/detections"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$year/$month/$day/detections": {
      "filePath": "$year/$month/$day/detections.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
