name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            vossccp/surveillance:latest
            vossccp/surveillance:${{ github.sha }}

      - name: GitOps - Checkout
        uses: actions/checkout@v4
        with:
          repository: vossccp/k8s
          ref: "master"
          token: ${{ secrets.K8S_PAT }}
          fetch-depth: 0
          path: vossccp.k8s

      - name: GitOps - Patch and push
        run: |
          git -C vossccp.k8s config user.name "vossccp"
          git -C vossccp.k8s config user.email "carsten.voss@gmx.de"
          sed -i "s|\(vossccp/surveillance:\)[^ ]*|\1${{ github.sha }}|" vossccp.k8s/home/surveillance.yaml
          git -C vossccp.k8s commit -am "surveillance: ${{ github.event.head_commit.message }}"
          git -C vossccp.k8s push origin master
